<a href="https://colab.research.google.com/github/hiba0903/DSA-Daily-Tasks/blob/main/DSA_Worksheet_D14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Find the Maximum of Three Numbers

In [ ]:
def max_of_three(a, b, c):
    return max(a, b, c)


In [ ]:
max_of_three(3,8,4)

8

2. Calculate the Area of a Circle

In [ ]:
import math

def area_of_circle(radius):
    return math.pi * radius ** 2

In [ ]:
area_of_circle(5)

78.53981633974483

3. Check if a Number is Prime

In [ ]:
def is_prime(n):
    if n <= 1:
        return False
    if n <= 3:
        return True
    if n % 2 == 0 or n % 3 == 0:
        return False
    i = 5
    while i * i <= n:
        if n % i == 0 or n % (i + 2) == 0:
            return False
        i += 6
    return True


In [ ]:
is_prime(87)

False

4. Check if a String is a Palindrome

In [ ]:
def is_palindrome(s):
    return s == s[::-1]


In [ ]:
is_palindrome('hello')

False

5. Calculate the Sum of All Numbers in a List

In [ ]:
def sum_of_list(lst):
    return sum(lst)


In [ ]:
sum([1,8,6,1,2,4])

22

6. Find the Average of a List of Numbers

In [ ]:
def average_of_list(lst):
    return sum(lst) / len(lst) if lst else 0


In [ ]:
average_of_list([8,2,9])

6.333333333333333

7. Find the k-th Largest Element in an Unsorted List

In [ ]:
import heapq

def kth_largest(lst, k):
    return heapq.nlargest(k, lst)[-1]


In [ ]:
kth_largest([8,3,6,4,10], 5)

3

8. Recursive Function to Find the Sum of Digits

In [ ]:
def sum_of_digits(n):
    if n == 0:
        return 0
    return n % 10 + sum_of_digits(n // 10)


In [ ]:
 sum_of_digits(636)

15

9. Recursive Function to Calculate the Power of a Number

In [ ]:
def power(base, exp):
    if exp == 0:
        return 1
    return base * power(base, exp - 1)


In [ ]:
power(2, 3)

8

10. Find the Greatest Common Divisor (GCD) Using Euclidean Algorithm

In [ ]:
def gcd(a, b):
    while b:
        a, b = b, a % b
    return a


In [ ]:
gcd(5,2)

1

11. Create a 1D Array of Numbers from 0 to 9

In [ ]:
import numpy as np

array_1d = np.arange(10)
print(array_1d)


[0 1 2 3 4 5 6 7 8 9]


12. Create a 2D Array of Shape (3, 3) with Values Ranging from 1 to 9

In [ ]:
array_2d = np.arange(1, 10).reshape(3, 3)
print(array_2d)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


13. Create a 3x3 Identity Matrix

In [ ]:
identity_matrix = np.eye(3)
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


14. Create an Array of 10 Random Numbers and Find the Mean and Standard Deviation

In [ ]:
random_array = np.random.rand(10)
mean = np.mean(random_array)
std_dev = np.std(random_array)

print(random_array)


[0.51482094 0.25366593 0.83932016 0.56755479 0.16385852 0.1964103
 0.56055667 0.19661298 0.56980515 0.11194406]


15. Create a 1D Array of Numbers from 10 to 20 and Extract the First 5 Elements

In [ ]:
array_15 = np.arange(10, 21)
first_5_elements = array_15[:5]
print(array_15)
print(first_5_elements)


[10 11 12 13 14 15 16 17 18 19 20]
[10 11 12 13 14]


16. Create a 2D Array of Shape (4, 4) and Extract the Second Row

In [ ]:
array_2d_4x4 = np.arange(16).reshape(4, 4)
second_row = array_2d_4x4[1]
print(array_2d_4x4)
print(second_row)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[4 5 6 7]


17. Create Two 1D Arrays of Length 5 with Values Ranging from 1 to 5 and 6 to 10. Perform Element-wise Addition

In [ ]:
array1 = np.arange(1, 6)
array2 = np.arange(6, 11)
elementwise_sum = array1 + array2

print(array1)
print(array2)

print(elementwise_sum)

[1 2 3 4 5]
[ 6  7  8  9 10]
[ 7  9 11 13 15]


18. Create a 1D Array of 10 Random Numbers and Replace All Elements Less Than 0.5 with 0

In [ ]:
random_array_18 = np.random.rand(10)
random_array_18[random_array_18 < 0.5] = 0

print(random_array_18)


[0.9082417  0.67055136 0.         0.         0.         0.
 0.         0.         0.64194999 0.99328975]
